= Wu Jiacheng - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: iScheduler Xs Max

---

== Overview

iScheduler Xs Max is a desktop scheduler application morphed from the original
https://github.com/nus-cs2103-AY1819S1/addressbook-level4[Address Book sample application (Level 4)]. As its name suggests, it is used for scheduling events and taskss. The user interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java, and has about 10 kLoC. +

This product is targetting at University students who have many tasks to handle such as homework deadlines, weekly lectures and tutorials, anniversaries with families and more. +

The postfix 'Xs Max' indicates a great improvement from the previous version of the product as it now supports Google Calendar! +

== Summary of contributions

* *Major enhancement*: added *the ability to manage tag and remark of events*
** What it does: allows the user to add or delete tag from events, and add additional remark to events.
** Justification: This feature improves the product significantly because users can organize their events better and provide extra information for events.
** Highlights: This enhancement affects existing commands and commands to be added in future. It required an in-depth analysis of design alternatives. The implementation too was challenging as it required changes to existing commands.
** Credits: PR from yamgent on remark command is referenced for the feature. https://github.com/se-edu/addressbook-level4/pull/599

* *Minor enhancement*: added customised commands for users: `deleteTag`, `remark`
that allow the users to more easily manage tag and remark of events.

* *Code contributed*: https://nus-cs2103-ay1819s1.github.io/cs2103-dashboard/#=undefined&search=jiacheng-panda[Project Code Dashboard]
*

* *Other contributions*:

** Project management:
*** Managed milestones
*** Maintained the issue trackers
** Documentation:
*** Update documentation for Tag and Remark Feature. Enhanced documentations for `add`, `edit` commands in the User Guide (Pull requests https://github.com/CS2103-AY1819S1-F11-1/main/pull/121[#121], https://github.com/CS2103-AY1819S1-F11-1/main/pull/258[#258], https://github.com/CS2103-AY1819S1-F11-1/main/pull/291[#291])

== Contributions to the User Guide

|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

3.9. Reminder Operations
include::../UserGuide.adoc[tag=Reminder Feature]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

3.9. Reminder Operations
include::../DeveloperGuide.adoc[tag=Reminder Feature]
